name: day01
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  aoc:
    path: ../_shared/aoc

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
