name: aoc_gen
description: Generates a template dart project for Advent of Code challenges.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  dcli: any

dev_dependencies:
  lints: ^4.0.0
