name: day09
description: Solution for Advent of Code 2024 Day 9
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.4

dependencies:
  aoc:
    path: ../_shared/aoc

dev_dependencies:
  lints: ^4.0.0